config/routes.rb
class VersionConstraint
  def initialize(*version)
    @version = version[0].to_i unless version.nil?
    @version = 2*100+1*10+1 if @version.nil? || @version ==0
  end

  def matches?(request)
    current_ver = request.query_parameters[:client_version]
    return false if current_ver.nil?
    current_ver_value = 0
    current_ver.split('.'). each_with_index do |v,i|
      break if i > 2
      current_ver_value += v.to_i*(10 ** (2-i))
    end
    return @version <= current_ver_value
  end
end

IntimeService::Application.routes.draw do

  get "comment/get_list"

  match "wxmsg/update"=>"wxReply#update"

  match "version/latest"=>"version#latest"
  match "version/insert"=>"version#insert"

  match "storecoupon/consume"=>"storeCoupon#consume"
  match "storecoupon/logs"=>"storeCoupon#logs"
  match "storecoupon/void"=>"storeCoupon#void"

  scope :module => "v22" do
    constraints VersionConstraint.new do
     match "promotion/list" =>"promotion#list"
     match "storepromotion/list"=>"storePromotion#list"
     match "storepromotion/detail"=>"storePromotion#detail"
     match "specialtopic/list"=>"specialTopic#list"
     match "banner/list"=>"banner#list"
    end
  end
  scope :module=>'front' do
    get '/auth/:provider/callback', to: 'sessions#create'
    delete '/logout', to: 'sessions#destory'
    get '/login', to: 'sessions#login'
  end

  match "hotword/list"=>"hotword#list"
  match "banner/list"=>"banner#list"

  match "store/list"=>"store#list"
  match "store/all"=>"store#list"
  match "store/detail"=>"store#detail"
  match "store/:id"=>"store#index"

  match "brand/list"=>"brand#list"
  match "brand/all"=>"brand#list"
  match "brand/groupall"=>"brand#list_by_group"

  match "tag/list"=>"tag#list"
  match "tag/all"=>"tag#list"

  match "specialtopic/list" => "specialTopic#list"

  match "product/search" => "product#search"
  match "product/list" => "product#list"

  match "promotion/list" => "promotion#list"

  match "wx_object/search" => "wxobject#validate", :via=>:get, :defaults=>{:format=>'html'}
  match "wx_object/search" => "wxobject#search", :via=>:post, :defaults=>{:format=>'xml'}

  match "card/find"=>"card#find"

  resources :special_topic, only: [:index] do
    collection do
      get :get_list
    end
  end

  resources :promotion, only: [] do
    collection do
      get :get_list
    end
  end

  scope module: :front do
    resources :promotions, only: [:index, :show] do
      collection do
        get :get_list
      end
    end

    resources :products, only: [:index, :show]
  end

  resources :special_topic, only: [:index] do
    collection do
      get :get_list
    end
  end

  resources :promotion, only: [] do
    collection do
      get :get_list
    end
  end

  scope module: :front do
    resources :promotions, only: [:index, :show] do
      collection do
        get :get_list
      end
    end

    resources :products, only: [:index, :show]
  end

  match "product/:id" => "product#show"
  match "promotion/:id" => "promotion#show"

  namespace :front do
       resources :exorders do
         collection do
           get 'show'
         end
       end

    get '/hotwords',                to: 'common#hotwords'
    get '/tags',                    to: 'common#tags'
    get '/brands',                  to: 'common#brands'
    get '/stores',                  to: 'common#stores'

    get '/my_favorite',             to: 'users_center#my_favorite'
    get '/my_share',                to: 'users_center#my_share'
    get '/my_promotion',            to: 'users_center#my_promotion'
    get '/follows',                 to: 'users_center#follows'
    get '/fans',                    to: 'users_center#fans'
    get '/my_profile',              to: 'users_center#profile'
    get '/his_favorite/:userid',    to: 'users_center#his_favorite',  as: :his_favorite
    get '/his_promotion/:userid',   to: 'users_center#his_promotion', as: :his_promotion
    get '/his_share/:userid',       to: 'users_center#his_share',     as: :his_share
    get '/his_info/:userid',        to: 'users_center#his_info',      as: :his_info
    get '/his_profile/:userid',     to: 'users_center#his_profile',   as: :his_profile
    post '/follow/:id',             to: 'users_center#follow',        as: :follow
    post '/unfollow/:id',           to: 'users_center#unfollow',      as: :unfollow
    get  '/about',                  to: 'about#index',                as: :about
    get  '/feedback',               to: 'about#feedback',             as: :feedback
    post '/feedback',               to: 'about#create_feedback',      as: :create_feedback

    get '/order/create' ,            to: 'orders#create'
    get 'address/create',           to: 'addresses#create'
    get 'address/update',           to: 'addresses#update'

    get  '/my_comments',            to: 'comments#my_comments',       as: :my_comments

    resources :products, :only=>[:index, :show] do
      collection do
        get :his_favorite_api, :path => :his_favorite_api
        get :my_favorite_api
        get :my_share_list_api
        get :sort_list
        get :list_api
        get :list
        get :search_api
      end

      member do
        post :favor
        post :unfavor
        post :download_coupon
        post :comment
      end
    end
    resources :promotions, :only=>[:index, :show] do
      collection do
        get :get_list
      end

      member do
        post :favor
        post :unfavor
        post :download_coupon
        post :comment
      end
    end

    resources :stores, only: [:show] do
      member do
        get :promotions
      end
    end

    resources :specials, :only => [:index] do
      collection do
        get :get_list
      end
    end

    resources :comments  do
      collection do
        get  :get_list
      end
    end

    resources :orders, except: [:edit, :update] do
      collection do
        post :computeamount
        post :confirm
      end

      member do
        get :pay
      end
    end
    resources :addresses, only: [:index, :create, :update, :destroy]
    resources :rmas do
      collection do
        get :order_index
      end
    end

    resources :coupons, only: [:index]

    resources :vouchers, only: [:index, :show] do
      collection do
        get  :exchange_info
        get  :binding_card

        post :bindcard
      end

      member do
        post :void
      end
    end

    resources :storepromotions, only: [:index, :show] do
      member do
        post :exchange
        post :amount
      end
    end
    get '/profile', to: 'profile#index'
    get '/profile/return_policy', to: 'profile#return_policy'
    get '/profile/edit', to: 'profile#edit'
    put '/profile/update', to: 'profile#update'

    get '/supportshipments', to: 'environment#supportshipments'

  end

  namespace :ims do

    resources :payments,only: [] do
      collection do
        get "go"
        get "alipay_success"
      end
    end

    resources :weixins, only: [] do
      collection do
        get "auth"
        get "login"
        get "login_success"
        get "get_access_token"
        get "qrcode"
      end
    end
    resources :sms_codes, only: :create
    resources :addresses do
      collection do
        get "list"
      end
    end

    resource :auth do
      get 'forward'
      get 'get_user_token'
    end
    resources :stores, only: [:show]
    resources :combos, only: [:show, :destroy, :index] do
      collection do
        post 'upload'
        get 'ajax'
      end
    end
    resources :accounts, only: [:new, :create] do
      collection do
        get   :mine
        get   :barcode
        get   :phone_page
        get   :verify_identify_phone
        get   :verify_identify_sms_code
        get   :verify_phone
        get   :verify_sms_code
        post  :resend_sms
        get   :set_identity_no_page
        get   :set_identity_no
        get   :before_reset_password_page
        get   :reset_password_page
        get   :reset_password
        get   :change_password_page
        get   :change_password
        get   :set_id_page
        post  :set_id
      end
    end
    resources :cards, only: [:index] do
      collection do
        get     :recharge
        get     :resend_gift
        get     :give_page
        get     :accept
        get     :accepted_page
        get     :give
        get     :refuse
        get     :agreement
      end
    end
    get 'cards/gift_page/:charge_no', to: 'cards#gift_page'
    resources :card_orders, only: [:new, :create, :show] do
      collection do
        get :list
        get :my_list
        get :received_list
        get :check_status
      end
    end
    match "card_orders_pay" => "card_orders#new"
    match "orders_new" => "orders#new"
    match "orders_show" => "orders#show"
    resources :favorites, only: [] do
      collection do
        get  :stores_list
        get  :combos_list
        get  :list
        post :favor
        post :unfavor
      end
    end
    resources :recharge_histroy, only: [:index]
    resources :orders, only: [:index, :new, :create, :show] do
      member do
        put :change_state
        post :payments
        get :notice_success
        put :update_promotion
      end

      collection do
        get :totalamount
      end
      resources :returns_reasons, only: [:new, :create] do
        member do
          put :cancel
        end
        collection do
          get "result"
        end
      end
    end

    

    namespace :store do
      root :to => "home#index"
      post "login" => "home#login"
      get 'check_code' => 'home#check_code'
      resources :invitation_codes, only: [:new, :create, :update] do
        collection do
          get :upgrade
        end
      end
      resources :sales_codes, only: :create
      resources :sells, only: :index do
        member do
          put :update_is_online
        end
      end
      resources :suggesstions, only: [:new, :create]
      resources :products do
        member do

app/controllers/front/about_controller.rb
# encoding: utf-8
class Front::AboutController < Front::BaseController

  def index
  end

  def feedback
  end

  def create_feedback
    @result = API::Feedback.create(request, params.slice(:content, :cantact))

    respond_to { |format| format.js }
  end

end

app/controllers/front/addresses_controller.rb
# encoding: utf-8
class Front::AddressesController < Front::BaseController
  before_filter :authenticate!

  # *output*
  # {
  #   page: 1,
  #   pagesize: 8,
  #   totalcount: 8,
  #   totalpaged: 1,
  #   datas: [
  #     {
  #       id: 1,                                               // 地址ID
  #       shippingperson: '涂马云',                            // 收获联系人
  #       shippingphone: '13011111111',                        // 送货联系电话
  #       shippingprovinceid: 1,                               // 省ID
  #       shippingprovince: '江西省',                          // 省
  #       shippingcityid: 1,                                   // 市ID
  #       shippingcity: '南昌市',                              // 市
  #       shippingdistrictid: 1,                               // 区ID
  #       shippingdistrict: '西湖区',                          // 区
  #       shippingaddress: 'xxx',                              // 送货地址
  #       shippingzipcode: '100000'                            // 邮编
  #     }
  #   ]
  # }
  def index
    @addresses = format_items(API::Address.index(request, page: 1, pagesize: 8)[:data], :page, :pagesize, :totalcount, :totalpaged)

    respond_to do |format|
      format.json { render json: @addresses, callback: params[:callback] }
      format.html
    end
  end

  # *input*
  # {
  #   order: {
  #     id: 1,                                               // 地址ID
  #     shippingperson: '涂马云',                            // 收获联系人
  #     shippingphone: '13011111111',                        // 送货联系电话
  #     shippingprovinceid: 1,                               // 省ID
  #     shippingprovince: '江西省',                          // 省
  #     shippingcityid: 1,                                   // 市ID
  #     shippingcity: '南昌市',                              // 市
  #     shippingdistrictid: 1,                               // 区ID
  #     shippingdistrict: '西湖区',                          // 区
  #     shippingaddress: 'xxx',                              // 送货地址
  #     shippingzipcode: '100000'                            // 邮编
  #   }
  # }
  #
  # *output*
  # - success
  # {
  #   isSuccessful: true,                                    // 用于判断更新是否成功
  #   statusCode: 200,
  #   message: '更新成功',                                   // 更新成功的信息
  #   data: {
  #     id: 1,                                               // 地址ID
  #     shippingperson: '涂马云',                            // 收获联系人
  #     shippingphone: '13011111111',                        // 送货联系电话
  #     shippingprovinceid: 1,                               // 省ID
  #     shippingprovince: '江西省',                          // 省
  #     shippingcityid: 1,                                   // 市ID
  #     shippingcity: '南昌市',                              // 市
  #     shippingdistrictid: 1,                               // 区ID
  #     shippingdistrict: '西湖区',                          // 区
  #     shippingaddress: 'xxx',                              // 送货地址
  #     shippingzipcode: '100000'                            // 邮编
  #   }
  # }
  # - fail
  # {
  #   isSuccessful: false,                                   // 用于判断更新是否成功
  #   statusCode: 500,
  #   message: '更新失败',                                   // 更新失败的信息
  # }
  def update
    params[:address][:shippingcontactperson] = params[:address].delete(:shippingperson)
    params[:address][:shippingcontactphone]  = params[:address].delete(:shippingphone)

    result = API::Address.update(request, params[:address].merge(id: params[:id]))
    render json: result.slice(:isSuccessful, :statusCode, :message, :data), callback: params[:callback]
  end

  # *input*
  # {
  #   order: {
  #     shippingperson: '涂马云',                            // 收获联系人
  #     shippingphone: '13011111111',                        // 送货联系电话
  #     shippingprovinceid: 1,                               // 省ID
  #     shippingprovince: '江西省',                          // 省
  #     shippingcityid: 1,                                   // 市ID
  #     shippingcity: '南昌市',                              // 市
  #     shippingdistrictid: 1,                               // 区ID
  #     shippingdistrict: '西湖区',                          // 区
  #     shippingaddress: 'xxx',                              // 送货地址
  #     shippingzipcode: '100000'                            // 邮编
  #   }
  # }
  # *output*
  # - success
  # {
  #   isSuccessful: true,                                    // 用于判断更新是否成功
  #   statusCode: 200,
  #   message: '创建成功',                                   // 创建成功的信息
  #   data: {
  #     id: 1,                                               // 地址ID
  #     shippingperson: '涂马云',                            // 收获联系人
  #     shippingphone: '13011111111',                        // 送货联系电话
  #     shippingprovinceid: 1,                               // 省ID
  #     shippingprovince: '江西省',                          // 省
  #     shippingcityid: 1,                                   // 市ID
  #     shippingcity: '南昌市',                              // 市
  #     shippingdistrictid: 1,                               // 区ID
  #     shippingdistrict: '西湖区',                          // 区
  #     shippingaddress: 'xxx',                              // 送货地址
  #     shippingzipcode: '100000'                            // 邮编
  #   }
  # }
  # - fail
  # {
  #   isSuccessful: false,                                   // 用于判断更新是否成功
  #   statusCode: 500,
  #   message: '创建失败',                                   // 创建失败的信息
  # }
  def create
    params[:address][:shippingcontactperson] = params[:address].delete(:shippingperson)
    params[:address][:shippingcontactphone]  = params[:address].delete(:shippingphone)

    result = API::Address.create(request, params[:address])
    render json: result.slice(:isSuccessful, :statusCode, :message, :data), callback: params[:callback]
  end

  def destroy
    result = API::Address.destroy(request, id: params[:id])
    render json: result.slice(:isSuccessful, :statusCode, :message, :data)
  end
end

app/controllers/front/common_controller.rb
# encoding: utf-8
class Front::CommonController < Front::BaseController

  def hotwords
    hotwords = Stage::HotWord.list
  end

  def stores
    stores = Stage::Store.list
    result = hotwords.slice(:storewords).merge(stores)
    get_all_brands(results)
    render :json => result.to_json, callback: params[:callback]
  end

  def brands
    brands     = Stage::Brand.group_brands
    all_brands = get_all_brands(brands[:brands])
    result     = hotwords.slice(:brandwords).merge(brands).merge(all_brands)
    render :json => result.to_json, callback: params[:callback]
  end

  def tags
    tags   = Stage::Tag.list
    result = hotwords.slice(:words).merge(tags)
    render :json => result.to_json, callback: params[:callback]
  end


end

app/controllers/front/environment_controller.rb
# encoding: utf-8
class Front::EnvironmentController < Front::BaseController

  # 省市区
  def supportshipments
    render json: format_items(API::Environment.supportshipments(request)[:data], :page, :pagesize, :totalcount, :totalpaged), callback: params[:callback]
  end
end

app/helpers/front/comment_helper.rb
# encoding: utf-8
module Front::CommentHelper

  def href_of_comment_item(comment)
    case comment[:sourcetype].to_i
    when 1
      front_product_path(comment[:sourceid])
    when 2
      front_promotion_path(comment[:sourceid])
    end
  end
end

app/views/front/_blank_prompt.html.erb
<% if defined? msg %>
  <div id="no_data" class="no_data alert alert-error text-center" style="display:block">
    <h5><i></i><%= msg -%></h5>
  </div>
<% end %>

app/views/front/_footer.html.erb
<footer>
<div class="container">
  <div class="pull-right">
    <a href="<%= root_url %>">首页</a>|
    <a href="<%= front_feedback_path -%>">意见反馈</a>|
    <a href="<%= front_about_path -%>">关于</a>
    <% if !signed_in? %>
      |<a href="<%= login_url %>">登录</a>
    <% end -%>
  </div>
  <div class="pull-left">Copyright © 2013 i.intime.com.cn. All Rights Reserved</div>
</div>
</footer>

app/views/front/_left_side.html.erb
<div class="sidenav">
  <div class="span3 aside collapse" >
    <div class="frame">
      <div class="section menu">
        <ul>
          <li <%= controller_name == 'promotions' ? "class=active" : '' -%>>
            <a href="<%= root_path -%>">促销专区</a>
          </li>
          <li <%= controller_name == 'specials' ? 'class=active' : '' -%>>
            <a href="<%= front_specials_path -%>">精彩专题</a>
          </li>
          <li><a href="<%= list_front_products_path %>">随便逛逛</a></li>
          <li><a href="<%= front_my_favorite_path %>">我的银泰</a></li>
        </ul>
      </div>
      <% if signed_in? %>
        <!--/已经登录位置 -->
        <div class="section loger">
          <div class="relative">
            <div class="photo">
              <a href="<%= front_my_profile_path %>"><img src="<%= current_user.avatar_url %>"></a>
            </div>
            <div class="tools">
              <span><%= current_user.nickie %><em><a href="<%= logout_path %>" data-method="delete" title="退出">退出</a></em></span>
              <ul><li><a href="<%= front_profile_path %>" title="预购中心"> </a></li>
                <li><a href="<%= front_my_comments_path -%>" title="消息"> </a></li>
                <li><a href="<%= front_profile_edit_path %>" title="设置"> </a></li>
                <li><a href="<%= logout_path %>" data-method="delete" title="退出"></a></li>
                <div class="clearfix"></div>
              </ul>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="share">
            <ul>
              <a href="<%= front_follows_path %>"><li>关注<br><%= current_user.like_count %></li></a>
              <a href="<%= front_fans_path %>"><li>粉丝<br><%= current_user.fans_count %></li></a>
              <a href="<%= front_coupons_path -%>"><li>优惠码<br><%= current_user.onlinecoupontotal %></li></a>
              <a href="<%= front_vouchers_path -%>"><li>兑换券<br>
                  <%= current_user.offlinecoupontotal %></li></a>
              <a href="<%= exchange_info_front_vouchers_path -%>"><li>积点<br>兑换</li></a>
              <div class="clearfix"></div>
            </ul>
          </div>
        </div><!--/已经登录位置 -->
      <% else %>
        <div class="section login">
          <h2>登录银泰</h2>
          <ul>
            <li><a href="<%= oauth_path('weibo') %>">新浪微博</a></li>
            <li><a href="<%= oauth_path('tqq2') %>">腾讯微博</a></li>
            <li><a href="<%= oauth_path('qq_connect') %>">腾讯QQ</a></li>
          </ul>
        </div>
      <% end %>
      <div class="section follow">
        <ul>
          <li><h2>下载APP</h2><a target="_blank" href="https://itunes.apple.com/cn/app/xi-huan-yin-tai-guang-shang/id615975780?mt=8"><img src="<%= static_url("images/ytapp.png") -%>" alt="下载喜欢银泰APP" width="51" height="51"></a></li>
          <li><h2>关注微信</h2><a href="#qrcode" data-toggle="modal"><img src="<%= static_url("images/icon_code.png") %>" alt="关注喜欢银泰微信" width="51" height="51"></a></li>
        </ul>
      </div>
    </div>
  </div>

  <div id="qrcode" class="modal hide fade" style="width: 260px;margin-left: -130px;" tabindex="-1" role="dialog" aria-labelledby="mLabel" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 id="mLabel">关注喜欢银泰微信</h3>
    </div>
    <div class="modal-body"><img src="<%= static_url("images/qrcode_200x200.jpg") %>"></div>
  </div>
</div>

app/views/front/_message.html.erb
<% if flash.notice.present? %>
  <div class="alert alert-success"><a class="close" data-dismiss="alert" href="#">x</a><%= flash.notice %></div>
<% elsif flash.alert.present? %>
  <div class="alert alert-error"><a class="close" data-dismiss="alert" href="#">x</a><%= flash.alert %></div>
<% end %>

app/views/front/no_login.js.erb
window.location.replace('<%= Settings.default_url_options.host -%>')