config/routes.rb
class VersionConstraint
  def initialize(*version)
    @version = version[0].to_i unless version.nil?
    @version = 2*100+1*10+1 if @version.nil? || @version ==0
  end

  def matches?(request)
    current_ver = request.query_parameters[:client_version]
    return false if current_ver.nil?
    current_ver_value = 0
    current_ver.split('.'). each_with_index do |v,i|
      break if i > 2
      current_ver_value += v.to_i*(10 ** (2-i))
    end
    return @version <= current_ver_value
  end
end

IntimeService::Application.routes.draw do

  get "comment/get_list"

  match "wxmsg/update"=>"wxReply#update"

  match "version/latest"=>"version#latest"
  match "version/insert"=>"version#insert"

  match "storecoupon/consume"=>"storeCoupon#consume"
  match "storecoupon/logs"=>"storeCoupon#logs"
  match "storecoupon/void"=>"storeCoupon#void"

  scope :module => "v22" do
    constraints VersionConstraint.new do
     match "promotion/list" =>"promotion#list"
     match "storepromotion/list"=>"storePromotion#list"
     match "storepromotion/detail"=>"storePromotion#detail"
     match "specialtopic/list"=>"specialTopic#list"
     match "banner/list"=>"banner#list"
    end
  end
  scope :module=>'front' do
    get '/auth/:provider/callback', to: 'sessions#create'
    delete '/logout', to: 'sessions#destory'
    get '/login', to: 'sessions#login'
  end

  match "hotword/list"=>"hotword#list"
  match "banner/list"=>"banner#list"

  match "store/list"=>"store#list"
  match "store/all"=>"store#list"
  match "store/detail"=>"store#detail"
  match "store/:id"=>"store#index"

  match "brand/list"=>"brand#list"
  match "brand/all"=>"brand#list"
  match "brand/groupall"=>"brand#list_by_group"

  match "tag/list"=>"tag#list"
  match "tag/all"=>"tag#list"

  match "specialtopic/list" => "specialTopic#list"

  match "product/search" => "product#search"
  match "product/list" => "product#list"

  match "promotion/list" => "promotion#list"

  match "wx_object/search" => "wxobject#validate", :via=>:get, :defaults=>{:format=>'html'}
  match "wx_object/search" => "wxobject#search", :via=>:post, :defaults=>{:format=>'xml'}

  match "card/find"=>"card#find"

  resources :special_topic, only: [:index] do
    collection do
      get :get_list
    end
  end

  resources :promotion, only: [] do
    collection do
      get :get_list
    end
  end

  scope module: :front do
    resources :promotions, only: [:index, :show] do
      collection do
        get :get_list
      end
    end

    resources :products, only: [:index, :show]
  end

  resources :special_topic, only: [:index] do
    collection do
      get :get_list
    end
  end

  resources :promotion, only: [] do
    collection do
      get :get_list
    end
  end

  scope module: :front do
    resources :promotions, only: [:index, :show] do
      collection do
        get :get_list
      end
    end

    resources :products, only: [:index, :show]
  end

  match "product/:id" => "product#show"
  match "promotion/:id" => "promotion#show"

  namespace :front do
       resources :exorders do
         collection do
           get 'show'
         end
       end

    get '/hotwords',                to: 'common#hotwords'
    get '/tags',                    to: 'common#tags'
    get '/brands',                  to: 'common#brands'
    get '/stores',                  to: 'common#stores'

    get '/my_favorite',             to: 'users_center#my_favorite'
    get '/my_share',                to: 'users_center#my_share'
    get '/my_promotion',            to: 'users_center#my_promotion'
    get '/follows',                 to: 'users_center#follows'
    get '/fans',                    to: 'users_center#fans'
    get '/my_profile',              to: 'users_center#profile'
    get '/his_favorite/:userid',    to: 'users_center#his_favorite',  as: :his_favorite
    get '/his_promotion/:userid',   to: 'users_center#his_promotion', as: :his_promotion
    get '/his_share/:userid',       to: 'users_center#his_share',     as: :his_share
    get '/his_info/:userid',        to: 'users_center#his_info',      as: :his_info
    get '/his_profile/:userid',     to: 'users_center#his_profile',   as: :his_profile
    post '/follow/:id',             to: 'users_center#follow',        as: :follow
    post '/unfollow/:id',           to: 'users_center#unfollow',      as: :unfollow
    get  '/about',                  to: 'about#index',                as: :about
    get  '/feedback',               to: 'about#feedback',             as: :feedback
    post '/feedback',               to: 'about#create_feedback',      as: :create_feedback

    get '/order/create' ,            to: 'orders#create'
    get 'address/create',           to: 'addresses#create'
    get 'address/update',           to: 'addresses#update'

    get  '/my_comments',            to: 'comments#my_comments',       as: :my_comments

    resources :products, :only=>[:index, :show] do
      collection do
        get :his_favorite_api, :path => :his_favorite_api
        get :my_favorite_api
        get :my_share_list_api
        get :sort_list
        get :list_api
        get :list
        get :search_api
      end

      member do
        post :favor
        post :unfavor
        post :download_coupon
        post :comment
      end
    end
    resources :promotions, :only=>[:index, :show] do
      collection do
        get :get_list
      end

      member do
        post :favor
        post :unfavor
        post :download_coupon
        post :comment
      end
    end

    resources :stores, only: [:show] do
      member do
        get :promotions
      end
    end

    resources :specials, :only => [:index] do
      collection do
        get :get_list
      end
    end

    resources :comments  do
      collection do
        get  :get_list
      end
    end

    resources :orders, except: [:edit, :update] do
      collection do
        post :computeamount
        post :confirm
      end

      member do
        get :pay
      end
    end
    resources :addresses, only: [:index, :create, :update, :destroy]
    resources :rmas do
      collection do
        get :order_index
      end
    end

    resources :coupons, only: [:index]

    resources :vouchers, only: [:index, :show] do
      collection do
        get  :exchange_info
        get  :binding_card

        post :bindcard
      end

      member do
        post :void
      end
    end

    resources :storepromotions, only: [:index, :show] do
      member do
        post :exchange
        post :amount
      end
    end
    get '/profile', to: 'profile#index'
    get '/profile/return_policy', to: 'profile#return_policy'
    get '/profile/edit', to: 'profile#edit'
    put '/profile/update', to: 'profile#update'

    get '/supportshipments', to: 'environment#supportshipments'

  end

  namespace :ims do

    resources :payments,only: [] do
      collection do
        get "go"
        get "alipay_success"
      end
    end

    resources :weixins, only: [] do
      collection do
        get "auth"
        get "login"
        get "login_success"
        get "get_access_token"
        get "qrcode"
      end
    end
    resources :sms_codes, only: :create
    resources :addresses do
      collection do
        get "list"
      end
    end

    resource :auth do
      get 'forward'
      get 'get_user_token'
    end
    resources :stores, only: [:show]
    resources :combos, only: [:show, :destroy, :index] do
      collection do
        post 'upload'
        get 'ajax'
      end
    end
    resources :accounts, only: [:new, :create] do
      collection do
        get   :mine
        get   :barcode
        get   :phone_page
        get   :verify_identify_phone
        get   :verify_identify_sms_code
        get   :verify_phone
        get   :verify_sms_code
        post  :resend_sms
        get   :set_identity_no_page
        get   :set_identity_no
        get   :before_reset_password_page
        get   :reset_password_page
        get   :reset_password
        get   :change_password_page
        get   :change_password
        get   :set_id_page
        post  :set_id
      end
    end
    resources :cards, only: [:index] do
      collection do
        get     :recharge
        get     :resend_gift
        get     :give_page
        get     :accept
        get     :accepted_page
        get     :give
        get     :refuse
        get     :agreement
      end
    end
    get 'cards/gift_page/:charge_no', to: 'cards#gift_page'
    resources :card_orders, only: [:new, :create, :show] do
      collection do
        get :list
        get :my_list
        get :received_list
        get :check_status
      end
    end
    match "card_orders_pay" => "card_orders#new"
    match "orders_new" => "orders#new"
    match "orders_show" => "orders#show"
    resources :favorites, only: [] do
      collection do
        get  :stores_list
        get  :combos_list
        get  :list
        post :favor
        post :unfavor
      end
    end
    resources :recharge_histroy, only: [:index]
    resources :orders, only: [:index, :new, :create, :show] do
      member do
        put :change_state
        post :payments
        get :notice_success
        put :update_promotion
      end

      collection do
        get :totalamount
      end
      resources :returns_reasons, only: [:new, :create] do
        member do
          put :cancel
        end
        collection do
          get "result"
        end
      end
    end

    

    namespace :store do
      root :to => "home#index"
      post "login" => "home#login"
      get 'check_code' => 'home#check_code'
      resources :invitation_codes, only: [:new, :create, :update] do
        collection do
          get :upgrade
        end
      end
      resources :sales_codes, only: :create
      resources :sells, only: :index do
        member do
          put :update_is_online
        end
      end
      resources :suggesstions, only: [:new, :create]
      resources :products do
        member do

app/controllers/front/about_controller.rb
# encoding: utf-8
class Front::AboutController < Front::BaseController

  def index
  end

  def feedback
  end

  def create_feedback
    @result = API::Feedback.create(request, params.slice(:content, :cantact))

    respond_to { |format| format.js }
  end

end

app/controllers/front/addresses_controller.rb
# encoding: utf-8
class Front::AddressesController < Front::BaseController
  before_filter :authenticate!

  # *output*
  # {
  #   page: 1,
  #   pagesize: 8,
  #   totalcount: 8,
  #   totalpaged: 1,
  #   datas: [
  #     {
  #       id: 1,                                               // 地址ID
  #       shippingperson: '涂马云',                            // 收获联系人
  #       shippingphone: '13011111111',                        // 送货联系电话
  #       shippingprovinceid: 1,                               // 省ID
  #       shippingprovince: '江西省',                          // 省
  #       shippingcityid: 1,                                   // 市ID
  #       shippingcity: '南昌市',                              // 市
  #       shippingdistrictid: 1,                               // 区ID
  #       shippingdistrict: '西湖区',                          // 区
  #       shippingaddress: 'xxx',                              // 送货地址
  #       shippingzipcode: '100000'                            // 邮编
  #     }
  #   ]
  # }
  def index
    @addresses = format_items(API::Address.index(request, page: 1, pagesize: 8)[:data], :page, :pagesize, :totalcount, :totalpaged)

    respond_to do |format|
      format.json { render json: @addresses, callback: params[:callback] }
      format.html
    end
  end

  # *input*
  # {
  #   order: {
  #     id: 1,                                               // 地址ID
  #     shippingperson: '涂马云',                            // 收获联系人
  #     shippingphone: '13011111111',                        // 送货联系电话
  #     shippingprovinceid: 1,                               // 省ID
  #     shippingprovince: '江西省',                          // 省
  #     shippingcityid: 1,                                   // 市ID
  #     shippingcity: '南昌市',                              // 市
  #     shippingdistrictid: 1,                               // 区ID
  #     shippingdistrict: '西湖区',                          // 区
  #     shippingaddress: 'xxx',                              // 送货地址
  #     shippingzipcode: '100000'                            // 邮编
  #   }
  # }
  #
  # *output*
  # - success
  # {
  #   isSuccessful: true,                                    // 用于判断更新是否成功
  #   statusCode: 200,
  #   message: '更新成功',                                   // 更新成功的信息
  #   data: {
  #     id: 1,                                               // 地址ID
  #     shippingperson: '涂马云',                            // 收获联系人
  #     shippingphone: '13011111111',                        // 送货联系电话
  #     shippingprovinceid: 1,                               // 省ID
  #     shippingprovince: '江西省',                          // 省
  #     shippingcityid: 1,                                   // 市ID
  #     shippingcity: '南昌市',                              // 市
  #     shippingdistrictid: 1,                               // 区ID
  #     shippingdistrict: '西湖区',                          // 区
  #     shippingaddress: 'xxx',                              // 送货地址
  #     shippingzipcode: '100000'                            // 邮编
  #   }
  # }
  # - fail
  # {
  #   isSuccessful: false,                                   // 用于判断更新是否成功
  #   statusCode: 500,
  #   message: '更新失败',                                   // 更新失败的信息
  # }
  def update
    params[:address][:shippingcontactperson] = params[:address].delete(:shippingperson)
    params[:address][:shippingcontactphone]  = params[:address].delete(:shippingphone)

    result = API::Address.update(request, params[:address].merge(id: params[:id]))
    render json: result.slice(:isSuccessful, :statusCode, :message, :data), callback: params[:callback]
  end

  # *input*
  # {
  #   order: {
  #     shippingperson: '涂马云',                            // 收获联系人
  #     shippingphone: '13011111111',                        // 送货联系电话
  #     shippingprovinceid: 1,                               // 省ID
  #     shippingprovince: '江西省',                          // 省
  #     shippingcityid: 1,                                   // 市ID
  #     shippingcity: '南昌市',                              // 市
  #     shippingdistrictid: 1,                               // 区ID
  #     shippingdistrict: '西湖区',                          // 区
  #     shippingaddress: 'xxx',                              // 送货地址
  #     shippingzipcode: '100000'                            // 邮编
  #   }
  # }
  # *output*
  # - success
  # {
  #   isSuccessful: true,                                    // 用于判断更新是否成功
  #   statusCode: 200,
  #   message: '创建成功',                                   // 创建成功的信息
  #   data: {
  #     id: 1,                                               // 地址ID
  #     shippingperson: '涂马云',                            // 收获联系人
  #     shippingphone: '13011111111',                        // 送货联系电话
  #     shippingprovinceid: 1,                               // 省ID
  #     shippingprovince: '江西省',                          // 省
  #     shippingcityid: 1,                                   // 市ID
  #     shippingcity: '南昌市',                              // 市
  #     shippingdistrictid: 1,                               // 区ID
  #     shippingdistrict: '西湖区',                          // 区
  #     shippingaddress: 'xxx',                              // 送货地址
  #     shippingzipcode: '100000'                            // 邮编
  #   }
  # }
  # - fail
  # {
  #   isSuccessful: false,                                   // 用于判断更新是否成功
  #   statusCode: 500,
  #   message: '创建失败',                                   // 创建失败的信息
  # }
  def create
    params[:address][:shippingcontactperson] = params[:address].delete(:shippingperson)
    params[:address][:shippingcontactphone]  = params[:address].delete(:shippingphone)

    result = API::Address.create(request, params[:address])
    render json: result.slice(:isSuccessful, :statusCode, :message, :data), callback: params[:callback]
  end

  def destroy
    result = API::Address.destroy(request, id: params[:id])
    render json: result.slice(:isSuccessful, :statusCode, :message, :data)
  end
end

app/controllers/front/common_controller.rb
# encoding: utf-8
class Front::CommonController < Front::BaseController

  def hotwords
    hotwords = Stage::HotWord.list
  end

  def stores
    stores = Stage::Store.list
    result = hotwords.slice(:storewords).merge(stores)
    get_all_brands(results)
    render :json => result.to_json, callback: params[:callback]
  end

  def brands
    brands     = Stage::Brand.group_brands
    all_brands = get_all_brands(brands[:brands])
    result     = hotwords.slice(:brandwords).merge(brands).merge(all_brands)
    render :json => result.to_json, callback: params[:callback]
  end

  def tags
    tags   = Stage::Tag.list
    result = hotwords.slice(:words).merge(tags)
    render :json => result.to_json, callback: params[:callback]
  end


end

app/controllers/front/environment_controller.rb
# encoding: utf-8
class Front::EnvironmentController < Front::BaseController

  # 省市区
  def supportshipments
    render json: format_items(API::Environment.supportshipments(request)[:data], :page, :pagesize, :totalcount, :totalpaged), callback: params[:callback]
  end
end

app/controllers/front/exorders_controller.rb
# encoding: utf-8
class Front::ExordersController < Front::BaseController 
  def show
    @product_name = params[:productname]
    @quantity = params[:quantity]
    @expdate = params[:expdate] || ''
    @remark = params[:remark] || ''
  end

end

app/views/front/vouchers/_binding_card.html.erb
<div class="vipright">
  <h2>我的会员卡</h2>
  <div class="content hui">
    <p class="hykind">
      <% if current_user.isbindcard -%>
        会员卡类型：<%= card[:lvl] -%><br>
        会员卡卡号：<%= card[:cardno] -%><br>
        会员卡总积点数：<%= card[:amount] -%>
      <% else -%>
        您还没有绑定会员卡<br>
        <a href="<%= binding_card_front_vouchers_path -%>" class="btn btn-danger">绑定</a>
      <% end -%>
    </p>
  </div>
</div>
<div class="clear"></div>

app/views/front/vouchers/_binding_info.html.erb
<div class="top">
  <div class="head_img"><span></span><img src="<%= current_user.avatar_url -%>"></div>
  <div class="cname">
    <p style="font-size:16px;"><%= current_user.nickie -%></p>
    <p style="font-size:12px;line-height: 20px;">
    <span>会员卡号：</span>
    <% if current_user.isbindcard -%>
      <%= card[:cardno] -%><br>
      <span>我的积点：</span><%= current_user.point + card[:amount].to_i -%>
    <% else -%>
      未绑定 <%= link_to '绑定', binding_card_front_vouchers_path, class: 'btn btn-danger' -%><br>
      <span>我的积点：</span><%= current_user.point -%>
    <% end -%>
    </p>
  </div>
  <div class="clearfix"></div>
</div>

app/views/front/vouchers/_new_vouchers.html.erb
<div class="vipleft">
  <h2><a href="<%= front_storepromotions_path -%>">最新积点兑换活动</a></h2>
  <div class="content">
    <% if storepromotion -%>
      <h3><em></em><%= storepromotion.name -%></h3>
      <p>参与门店：<%= storepromotion.storenames -%><br>
      活动时间：<%= format_time_range(@storepromotion.activestartdate, @storepromotion.activeenddate) -%>
      </p>
      <p style="text-align:center; padding-top:5px;">
      <%= link_to '兑换', front_storepromotion_path(storepromotion.id), class: 'btn btn-danger' -%>
      </p>
    <% else -%>
      <p style="text-align:center; line-height:40px; font-size:14px;">暂无最新积点兑换活动！</p>
    <% end -%>
  </div>
</div>

app/views/front/vouchers/_score_record.html.erb
<div class="bottom">
  <h2>我的积点记录</h2>
  <ul>
    <li>恭喜您注册成功获得100积点<span>2013-02-28</span></li>
    <li>恭喜您注册成功获得200积点<span>2013-02-20</span></li>
  </ul>
</div>

app/views/front/vouchers/binding_card.html.erb
<%= content_for :head_nav do -%>
  <ul class="nav">
    <li><a href="<%= exchange_info_front_vouchers_path -%>"><i class="icon-undo"></i></a></li>
    <li class="title">会员卡绑定</li>
  </ul>
<% end -%>
<div class="span9 main">
  <% if flash[:notice] -%>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] -%>
    </div>
  <% end -%>
  <div class="details omjd hykbd">
    <%= form_tag bindcard_front_vouchers_path, method: :post do -%>
      <div class="bdtd">
        <p><span>卡号：</span>
        <%= text_field_tag :cardno, nil, placeholder: '请输入您的会员卡卡号' -%>
        </p>
        <p><span>密码：</span>
        <%= password_field_tag :password, nil, placeholder: '请输入您的会员卡密码' -%>
        </p>
        <p>
        <a href="#barcode" data-toggle="modal" class="btn btn-danger ">绑定</a>
        </p>
        <div id="barcode" class="modal hide fade in" tabindex="-1" role="dialog" aria-labelledby="barcode" aria-hidden="false">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="mLabel">会员卡绑定</h3>
          </div>
          <div class="modal-body">
            <p>您确定要绑定会员卡吗？</p>
          </div>
          <div class="modal-footer">
            <%= submit_tag '确认', class: 'btn btn-danger', 'aria-hidden' => 'true' -%>
            <a class="btn " data-dismiss="modal" aria-hidden="true">取消</a> </div>
        </div>
      </div>
    <% end -%>
  </div>
</div>

app/views/front/vouchers/exchange_info.html.erb
<%= content_for :head_nav do -%>
  <ul class="nav">
    <li><a href="<%= front_his_info_path(current_user.id) -%>"><i class="icon-undo"></i></a></li>
    <li class="title">积点兑换</li>
  </ul>
<% end -%>
<div class="span9 main">
  <div class="details omjd jddh">
    <%= render 'binding_info', card: @card -%>

    <div class="ct">
      <%= render 'new_vouchers', storepromotion: @storepromotion -%>
      <%= render 'binding_card', card: @card -%>
    </div>
    <div class="bottom">
      <h2>我的积点记录</h2>
      <ul>
        <% if @records.present? -%>
          <% @records.each do |point| -%>
            <li><%= point['name'] -%><span><%= format_time(point['createddate']) -%></span></li>
          <% end -%>
        <% else -%>
          <li>暂无积点记录！</li>
        <% end -%>
      </ul>
    </div>
    <%= paginate @records -%>
  </div>
</div>

app/views/front/vouchers/index.html.erb
<%= content_for :head_nav do -%>
  <ul class="nav">
    <li><a href="<%= front_my_favorite_path -%>"><i class="icon-undo"></i></a></li>
    <li><a href="<%= front_vouchers_path(type: 1) -%>" id="recently">未使用<span class="ycmenu">的兑换券(<%= @recent_vouchers['totalpaged'] -%>)</span></a></li>
    <li><a href="<%= front_vouchers_path(type: 2) -%>" id="news">已使用<span class="ycmenu">的兑换券(<%= @news_vouchers['totalpaged'] -%>)</span></a></li>
    <li><a href="<%= front_vouchers_path(type: 3) -%>" id="future">已过期<span class="ycmenu">的兑换券(<%= @expire_vouchers['totalpaged'] -%>)</span></a></li>
  </ul>
<% end -%>
<div class="span9 main">
  <section class="portfolio ">
  <div id="div" class="Coupon">
    <ul class="thumbnails">
      <% if @vouchers.present? -%>
        <% @vouchers.each do |voucher| -%>
          <li> <a href="<%= front_voucher_path(voucher[:id]) -%>">
            <div class="thumbnail">
              <span class="hdname"><%= voucher[:promotion][:name] %></span>
              <span class="yxdate">有效期:<%= format_time_range(voucher[:validstartdate], voucher[:validenddate]) -%></span>
              <span class="dpname">礼券面额：<em><%= voucher[:amount] -%>元</em></span>
              <span class="yhm"><b><%= voucher[:code] -%><em></em></b></span>
            </div>
          </a> </li>
        <% end -%>

        <%= paginate @vouchers -%>
      <% else -%>
        <p style="text-align:center;font-size: 16px;line-height:30px;">
        暂无兑换券
        </p>
      <% end -%>
    </ul>
  </div>
  </section>
</div>

app/views/front/vouchers/show.html.erb
<%= content_for :head_nav do -%>
  <ul class="nav">
    <li><a href="javascript:history.go(-1);"><i class="icon-undo"></i></a></li>
    <li class="title">兑换券信息</li>
  </ul>
<% end -%>
<div class="span9 main">
  <div class="details cfxq">
    <div class="vipleft">
      <h2><em></em><%= @voucher[:promotion][:name] -%></h2>
      <div class="content">
        <p class="lqm">礼券码：<%= @voucher[:code] -%></p>
        <p class="bb b10"> <span>领兑时间：</span><%= format_time(@voucher[:createddate]) -%><br>
        <span>礼券有效期：</span><%= format_date(@voucher[:validenddate]) -%>止<br>
        <span>使用门店：</span><%= @voucher[:promotion][:inscopenotice].map{|item| item[:storename]}.join(',') -%><br>
        <span>兑换积点：</span><%= @voucher[:points] -%><br>
        <span>兑换金额：</span><b style="color:#D10149;"><%= @voucher[:amount] -%>元</b><br>
        <em class="xr">特别提醒：<%= format_newline(@voucher[:promotion][:usagenotice]) -%></em> </p>
        <% @voucher[:promotion][:inscopenotice].each do |_item| -%>
          <p> <span>使用门店：</span><%= _item[:storename] -%><br>
          </p><div class="xh"><%= format_newline(_item[:excludes]) -%></div>
          <p></p>
        <% end -%>
      </div>
    </div>
    <div class="vipright">
      <h2>　</h2>
      <div class="content">
        <p>注意事项</p>
        <p class="xh"><%= format_newline(@voucher[:promotion][:notice]) -%></p>
      </div>
    </div>
    <div class="clear">
      <p class="center" style="padding-top:20px;"> <a href="#barcode" data-toggle="modal" class="btn btn-danger ">取消兑换</a>
      </p><div id="barcode" class="modal hide fade in" tabindex="-1" role="dialog" aria-labelledby="barcode" aria-hidden="false">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="mLabel">取消兑换</h3>
      </div>
      <div class="modal-body">
        <p>您是否确定要取消兑换？</p>
      </div>
      <div class="modal-footer">
        <%= link_to '确认', void_front_voucher_path(@voucher[:id]), class: 'btn btn-danger', 'data-dismiss' => 'modal', 'aria-hidden' => 'true', method: :post -%>
        <a class="btn" data-dismiss="modal" aria-hidden="true">取消</a>
      </div>
    </div>
    <p></p>
  </div>
</div>
    </div>