config/routes.rb
    delete '/logout', to: 'sessions#destory'
    get '/login', to: 'sessions#login'
  end

  match "hotword/list"=>"hotword#list"
  match "banner/list"=>"banner#list"

  match "store/list"=>"store#list"
  match "store/all"=>"store#list"
  match "store/detail"=>"store#detail"
  match "store/:id"=>"store#index"

  match "brand/list"=>"brand#list"
  match "brand/all"=>"brand#list"
  match "brand/groupall"=>"brand#list_by_group"

  match "tag/list"=>"tag#list"
  match "tag/all"=>"tag#list"

  match "specialtopic/list" => "specialTopic#list"

  match "product/search" => "product#search"
  match "product/list" => "product#list"

  match "promotion/list" => "promotion#list"

  match "wx_object/search" => "wxobject#validate", :via=>:get, :defaults=>{:format=>'html'}
  match "wx_object/search" => "wxobject#search", :via=>:post, :defaults=>{:format=>'xml'}

  match "card/find"=>"card#find"

  resources :special_topic, only: [:index] do
    collection do
      get :get_list
    end
  end

  resources :promotion, only: [] do
    collection do
      get :get_list
    end
  end

  scope module: :front do
    resources :promotions, only: [:index, :show] do
      collection do
        get :get_list
      end
    end

    resources :products, only: [:index, :show]
  end

  resources :special_topic, only: [:index] do
    collection do
      get :get_list
    end
  end

  resources :promotion, only: [] do
    collection do
      get :get_list
    end
  end

  scope module: :front do
    resources :promotions, only: [:index, :show] do
      collection do
        get :get_list
      end
    end

    resources :products, only: [:index, :show]
  end

  match "product/:id" => "product#show"
  match "promotion/:id" => "promotion#show"

  namespace :front do
       resources :exorders do
         collection do
           get 'show'
         end
       end

    get '/hotwords',                to: 'common#hotwords'
    get '/tags',                    to: 'common#tags'
    get '/brands',                  to: 'common#brands'
    get '/stores',                  to: 'common#stores'

    get '/my_favorite',             to: 'users_center#my_favorite'
    get '/my_share',                to: 'users_center#my_share'
    get '/my_promotion',            to: 'users_center#my_promotion'
    get '/follows',                 to: 'users_center#follows'
    get '/fans',                    to: 'users_center#fans'
    get '/my_profile',              to: 'users_center#profile'
    get '/his_favorite/:userid',    to: 'users_center#his_favorite',  as: :his_favorite
    get '/his_promotion/:userid',   to: 'users_center#his_promotion', as: :his_promotion
    get '/his_share/:userid',       to: 'users_center#his_share',     as: :his_share
    get '/his_info/:userid',        to: 'users_center#his_info',      as: :his_info
    get '/his_profile/:userid',     to: 'users_center#his_profile',   as: :his_profile
    post '/follow/:id',             to: 'users_center#follow',        as: :follow
    post '/unfollow/:id',           to: 'users_center#unfollow',      as: :unfollow
    get  '/about',                  to: 'about#index',                as: :about
    get  '/feedback',               to: 'about#feedback',             as: :feedback
    post '/feedback',               to: 'about#create_feedback',      as: :create_feedback

    get '/order/create' ,            to: 'orders#create'
    get 'address/create',           to: 'addresses#create'
    get 'address/update',           to: 'addresses#update'

    get  '/my_comments',            to: 'comments#my_comments',       as: :my_comments

    resources :products, :only=>[:index, :show] do
      collection do
        get :his_favorite_api, :path => :his_favorite_api
        get :my_favorite_api
        get :my_share_list_api
        get :sort_list
        get :list_api
        get :list
        get :search_api
      end

      member do
        post :favor
        post :unfavor
        post :download_coupon
        post :comment
      end
    end
    resources :promotions, :only=>[:index, :show] do
      collection do
        get :get_list
      end

      member do
        post :favor
        post :unfavor
        post :download_coupon
        post :comment
      end
    end

    resources :stores, only: [:show] do
      member do
        get :promotions
      end
    end

    resources :specials, :only => [:index] do
      collection do
        get :get_list
      end
    end

    resources :comments  do
      collection do
        get  :get_list
      end
    end

    resources :orders, except: [:edit, :update] do
      collection do
        post :computeamount
        post :confirm
      end

      member do
        get :pay
      end
    end
    resources :addresses, only: [:index, :create, :update, :destroy]
    resources :rmas do
      collection do
        get :order_index
      end
    end

    resources :coupons, only: [:index]

    resources :vouchers, only: [:index, :show] do
      collection do
        get  :exchange_info
        get  :binding_card

        post :bindcard
      end

      member do
        post :void
      end
    end

    resources :storepromotions, only: [:index, :show] do
      member do
        post :exchange
        post :amount
      end
    end
    get '/profile', to: 'profile#index'
    get '/profile/return_policy', to: 'profile#return_policy'
    get '/profile/edit', to: 'profile#edit'
    put '/profile/update', to: 'profile#update'

    get '/supportshipments', to: 'environment#supportshipments'

  end

  namespace :ims do

    resources :payments,only: [] do
      collection do
        get "go"
        get "alipay_success"
      end
    end

    resources :weixins, only: [] do
      collection do
        get "auth"
        get "login"
        get "login_success"
        get "get_access_token"
        get "qrcode"
      end
    end
    resources :sms_codes, only: :create
    resources :addresses do
      collection do
        get "list"
      end
    end

    resource :auth do
      get 'forward'
      get 'get_user_token'
    end
    resources :stores, only: [:show]
    resources :combos, only: [:show, :destroy, :index] do
      collection do
        post 'upload'
        get 'ajax'
      end
    end
    resources :accounts, only: [:new, :create] do
      collection do
        get   :mine
        get   :barcode
        get   :phone_page
        get   :verify_identify_phone
        get   :verify_identify_sms_code
        get   :verify_phone
        get   :verify_sms_code
        post  :resend_sms
        get   :set_identity_no_page
        get   :set_identity_no
        get   :before_reset_password_page
        get   :reset_password_page
        get   :reset_password
        get   :change_password_page
        get   :change_password
        get   :set_id_page
        post  :set_id
      end
    end
    resources :cards, only: [:index] do
      collection do
        get     :recharge
        get     :resend_gift
        get     :give_page
        get     :accept
        get     :accepted_page
        get     :give
        get     :refuse
        get     :agreement
      end
    end
    get 'cards/gift_page/:charge_no', to: 'cards#gift_page'
    resources :card_orders, only: [:new, :create, :show] do
      collection do
        get :list
        get :my_list
        get :received_list
        get :check_status
      end
    end
    match "card_orders_pay" => "card_orders#new"
    match "orders_new" => "orders#new"
    match "orders_show" => "orders#show"
    resources :favorites, only: [] do
      collection do
        get  :stores_list
        get  :combos_list
        get  :list
        post :favor
        post :unfavor
      end
    end
    resources :recharge_histroy, only: [:index]
    resources :orders, only: [:index, :new, :create, :show] do
      member do
        put :change_state
        post :payments
        get :notice_success
        put :update_promotion
      end

      collection do
        get :totalamount
      end
      resources :returns_reasons, only: [:new, :create] do
        member do
          put :cancel
        end
        collection do
          get "result"
        end
      end
    end

    

    namespace :store do
      root :to => "home#index"
      post "login" => "home#login"
      get 'check_code' => 'home#check_code'
      resources :invitation_codes, only: [:new, :create, :update] do
        collection do
          get :upgrade
        end
      end
      resources :sales_codes, only: :create
      resources :sells, only: :index do
        member do
          put :update_is_online
        end
      end
      resources :suggesstions, only: [:new, :create]
      resources :products do
        member do
          get 'add_to_combo'
        end
        collection do
          post :upload
          get :search
          get :add_size
        end
      end
      resources :combos do
        member do
          put 'add_img'
          put 'update_desc'
          get 'preview'
          get 'update_desc'
        end
        collection do
          get 'remove_img'
          get 'remove_product'
        end
      end
      resources :stores, only: [:show, :edit, :update] do
        collection do
          get 'records', 'theme', 'check', 'change_theme'
          post 'change_logo'
        end
        member do
          get 'my'
        end
      end
      resources :incomes, only: [:index, :new, :create] do
        collection do
          get :my, :list, :frozen, :tips, :pending
        end
      end

    end

    resource :app,only:[] do
      member do
        post :token
      end
    end
  end

  get 'payment/callback', to: 'front/orders#pay_callback'
  match "product/:id" => "product#show"
  match "promotion/:id" => "promotion#show"

  match "ims/combos/:id/:t" => "ims/combos#show", as: "ims_combo"
  match "ims/stores/:id/:t" => "ims/stores#show", as: "ims_store"

app/models/combo.rb
# encoding: utf-8
class Combo < ActiveRecord::Base
  DOCUMENT_TYPE = "escombos"

  attr_accessible :desc, :remote_id, :combo_type, :private_to, :has_discount, :discount, :is_public

  has_many :combo_pics
  has_many :combo_products

  default_value_for :is_public, false

  def api_attrs
  	{
  	 	:desc => desc,
  	 	:private_to => private_to,
  	 	:productids => combo_products.map(&:remote_id).uniq.compact,
  	 	:image_ids => combo_pics.map(&:remote_id).uniq.compact,
  	 	:product_type => combo_products.first.product_type,
      :has_discount => has_discount,
      :discount => discount,
      :is_public => is_public
  	}
  end

  def product_desc
    combo_products.map {|x| "#{x.brand_name}#{x.category_name}"}.uniq.compact.join(",")
  end

  def self.img_url(combo)
    resource = combo['resources'].find do |resource|
      resource.try(:[], :name).present?
    end
    if resource.present?
      img_url = [PIC_DOMAIN, resource['name'], "_320x0.jpg"].join('')
    else
      Settings.default_image_url.product.middle
    end
  end

  def can_edit_pro?
    combo_products.all?{|product| product.product_type == "2"}
  end

  include Tire::Model::Search
  extend Searchable
  index_name ES_DEFAULT_INDEX
  document_type DOCUMENT_TYPE

  def self.es_search(options={})
    keywords = options[:keywords]
    store_id = options[:store_id]
    group_id = options[:group_id]
    per_page = options[:per_page].present? ? options[:per_page].to_i : 10
    page = options[:page].present? ? options[:page].to_i : 1
    query = Jbuilder.encode do |json|

      if keywords.present?
        json.query do
          json.query_string do
            json.fields ['brands.name^2','associateName']
            json.query keywords
            json.use_dis_max true
            json.minimum_should_match '75%'
          end
        end
      end

      json.filter do
        json.and do
          json.child! do
            json.range do
              json.expireDate do
                json.gt Time.now
              end
            end
          end

          json.child! do
            json.term do
              json.status 1
            end
          end


          if store_id.present?
            json.child! do
              json.term do
                json.storeId store_id
              end
            end
          end

          if group_id.present?
            json.child! do
              json.term do
                json.set! 'group.id', group_id
              end
            end
          end

        end
      end
      if !keywords.present?
        json.sort do
          json.createDate "desc"
        end
      end

    end
    result = $client.search index: ES_DEFAULT_INDEX, type: DOCUMENT_TYPE, size: per_page, from: (page-1) * per_page, body: query
    mash = Hashie::Mash.new result
    {count: mash.hits.total, page: page, per_page: per_page, group_id: group_id, data: mash.hits.hits.collect(&:_source)}
  end
end

app/models/ims/assistant.rb
# encoding: utf-8
class Ims::Assistant < Ims::Base

  def self.update_is_online(req, params = {})
    post(req, params.merge(path: 'assistant/combo_status_update'))
  end

  def self.brands(req, params={})
    post(req, params.merge(path: 'assistant/brands'))
  end

end

app/models/ims/base.rb
# encoding: utf-8
class Ims::Base
  extend Ims::Restful

end

app/models/ims/combo.rb
# encoding: utf-8
class Ims::Combo < Ims::Base

  class << self
    def list(req, params={})
      post(req, params.merge(path: 'assistant/combos'))
    end

    def create(req, params={})
      post(req, params.merge(path: 'combo/create', content_type: :json))
    end

    def show(req, params = {})
      post(req, params.merge(path: 'combo/detail'))
    end

    def update(req, params = {})
      post(req, params.merge(path: 'combo/update', content_type: :json))
    end

    def upload_img(req, params ={})
      post(req, params.merge(path: 'resource/upload'))
    end

    def online_num(req, params = {})
      post(req, params.merge(path: 'assistant/combos_online_count'))
    end

    def delete(req, params = {})
      post(req, params.merge(path: 'combo/delete'))
    end

  end

end

app/models/ims/des.rb
# encoding: utf-8
class Ims::Des
  require 'openssl'  
  require 'base64'  
  ALG = 'DES-ECB'  
  KEY = "intimeit"     #你的密钥
  DES_KEY = "intimeit"          #任意固定的值
  
  #加密  
  def encode(str)  
    des = OpenSSL::Cipher::Cipher.new(ALG)  
    des.encrypt
    des.key=KEY
    cipher = des.update(str)  
    cipher << des.final  
    return Base64.encode64(cipher) #Base64编码，才能保存到数据库
  end  
  
  #解密    
  def decode(str)  
    str = Base64.decode64(str)  
    des = OpenSSL::Cipher::Cipher.new(ALG)  
    des.pkcs5_keyivgen(KEY, DES_KEY)  
    des.decrypt  
    des.update(str) + des.final  
  end  
end

app/models/ims/giftcard.rb
# encoding: utf-8
class Ims::Giftcard < Ims::Base

  # 默认礼品卡Id
  DEFAULT_ID = '1'

  # 导购获取可选择礼品卡列表
  def self.all(req, params = {})
    post(req, params.merge(path: "assistant/gift_cards"))
  end

  # 普通用户-已绑定卡的礼品卡概述（在API部门是否绑定）
  def self.my(req, params = {})
    post(req, params.merge(path: 'giftcard/my'))
  end

  # 普通用户通过手机号得到卡信息，同时进行绑定
  def self.bind(req, params = {})
    post(req, params.merge(path: 'giftcard/bind'))
  end

  # 判断手机号是否已经绑定（在集团信息部是否绑定）
  def self.isbind(req, params = {})
    post(req, params.merge(path: 'giftcard/isbind'))
  end

  def self.create(req, params = {})
    post(req, params.merge(path: 'giftcard/create'))
  end

  # 普通用户购买充值卡，列表
  def self.items(req, params = {})
    post(req, params.merge(path: 'giftcard/items'))
  end

  # 普通用户购买充值卡
  def self.transfer_detail(req, params = {})
    post(req, params.merge(path: 'giftcard/transfer_detail'))
  end

  # 获取礼品卡赠送信息 通过赠送记录 id
  def self.trans_detail2(req, params = {})
    post(req, params.merge(path: 'giftcard/trans_detail2'))
  end

  def self.detail(req, params = {})
    post(req, params.merge(path: 'giftcard/detail'))
  end

  def self.trans_detail(req, params = {})
    post(req, params.merge(path: 'giftcard/trans_detail'))
  end

  def self.receive(req, params = {})
    post(req, params.merge(path: 'giftcard/receive'))
  end

  def self.recharge(req, params = {})
    post(req, params.merge(path: 'giftcard/recharge'))
  end

  def self.send(req, params = {})
    post(req, params.merge(path: 'giftcard/send'))
  end

  def self.sendex(req, params = {})
    post(req, params.merge(path: 'giftcard/sendex'))
  end

  def self.changepwd(req, params = {})
    post(req, params.merge(path: 'giftcard/change_pwd'))
  end

  def self.resetpwd(req, params = {})
    post(req, params.merge(path: 'giftcard/reset_pwd'))
  end

  def self.refuse(req, params = {})
    post(req, params.merge(path: 'giftcard/refuse'))
  end

  def self.refusebytransid(req, params = {})
    post(req, params.merge(path: 'giftcard/refusebytransid'))
  end

  def self.list(req, params = {})
    post(req, params.merge(path: 'giftcard/list'))
  end

end

app/models/ims/income.rb
# encoding: utf-8

class Ims::Income < Ims::Base

  class << self

    def index(req, params={})
      post(req, params.merge(path: 'assistant/income_history'))
    end

    def list(req, params={})
      post(req, params.merge(path: 'assistant/income_received'))
    end

    def frozen(req, params={})
      post(req, params.merge(path: 'assistant/income_frozen'))
    end

    def my(req, params={})
   	  post(req, params.merge(path: 'assistant/income'))
    end

    def banks(req, params = {})
      post(req, params.merge(path: 'assistant/avail_banks'))
    end

    def apply(req, params = {})
      post(req, params.merge(path: 'assistant/income_request'))
    end

    def pending(req, params = {})
      post(req, params.merge(path: 'assistant/income_requesting'))
    end

    def latest_bank(req, params = {})
      post(req, params.merge(path: 'assistant/latest_bankinfo'))
    end
  end

end

app/models/ims/sms.rb
# encoding: utf-8
class Ims::Sms < Ims::Base

  def self.send(req, params = {})
    post(req, params.merge(path: 'sms/send'))
  end

end

app/views/ims/combos/_ajax.html.erb
    <div class="xclose clearfix"><button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times"></i></button></div>
    <div class="modal-content">

      <div class="p-modal-body">

        <div class="swiper-container" id="p-swiper">
          <div class="swiper-wrapper">
            <% product = @product %>
            <% salecolors = product["isSystem"] ? product[:resources].reverse : product[:resources] %>
            <% if salecolors.present? %>
              <% salecolors.each do |color| %>
              <% img_url = Product.img_url(color) %>
              <div class="swiper-slide">
                <%= image_tag img_url %>
              </div>
              <% end %>
            <% else %>
              <% img_url = Product.img_url(nil.try(:[], :resource)) %>
              <div class="swiper-slide">
              <%= image_tag img_url %>
              </div>
            <% end %>
          </div>
        </div>

      </div>
  </div>
  <div class="clearfix"></div>
  <div class="p-modal-desc" id="p-modal-desc">
      <p class="txt1"><%= product[:name] %></p>
      <p class="txt3"><%= product["description"] %></p>
      <div class="desc-txt">
        <p class='pull-left'>
          <span class="txt1">微信价： <i class="txt-red">￥<%= product[:price] %></i></span>
          <span class="txt3"><%= "￥#{product[:unitprice]}" if product[:unitprice] %></span>
        </p>
        <p class="pull-right">
          <% if @combo[:is_online] && product[:is4sale] %><%= link_to "点击购买", 'javascript:void(0);', class: "btn btn-danger btn-small loading-box", value: ims_orders_new_path(:product_id => product[:id], :store_id => @store_id, combo_id: @combo[:id]) %>
          <% end %>
        </p>
      </div>
      <div class="clearfix"></div>
    </div>
  <script type="text/javascript">
  $(function(){
   $(".xclose").on('click', function(){
      $("#p_pop").modal('hide');
    });

   $(".p-modal-desc .loading-box").on("click", function(){
      url = $(this).attr("value")
      $("#loading-box").modal()
      setTimeout(function(){
        window.location.href = url
      }, 1)
    })
  });
  </script>

app/views/ims/combos/_content.html.erb
<% if @combos.count == 0 %>

<%= render 'ims/shared/empty' %>

<% else %>

<% @combos.each do |combo| %>
<div class="module module-ele">
  <div class="module-content module-content-img">
    <div class="suit-box clearfix">
      <div class="row-fluid">
        <div class="span12">
          <div class="suit-left">
            <a class="img-box img-posi add_loading" href="javascript:void(0);" value="<%= ims_combo_path(id: combo["id"], t: Time.now.to_i) %>">
              <%= image_tag Combo.img_url(combo) %>
            </a>

            <p><a href="<%= ims_combo_path(id: combo["id"], t: Time.now.to_i) %>"><%= sanitize format_text(combo["desc"]) %></a></p>
          </div>
        </div>
      </div>
    </div>

    <div class="clearfix countdown-browser">
      <p class="pull-left price-box">
        <span class="txt3 price price-span">
          打包价：<em>¥<%= BigDecimal(combo["price"].to_s) - BigDecimal(combo["discountAmount"].to_s) %></em>
        </span>
      </p>
      <p class="pull-left price-box">
        <% expired_in = (combo["expireDate"].to_time - 8.hour).to_i - Time.now.to_i
        expired_in = expired_in > 0 ? expired_in : nil %>
        <% if expired_in.present? %>
        <span class="pull-left countdown">
          <em id="d<%=combo['id']%>">0</em><span>天</span><em id="h<%=combo['id']%>">00</em>:<em id="m<%=combo['id']%>">00</em>:<em id="s<%=combo['id']%>">00</em><span>后下架</span>
        </span>
        <script type="text/javascript">
          tms[tms.length] = "<%=expired_in %>";
          day[day.length] = "d<%=combo['id']%>";
          hour[hour.length] = "h<%=combo['id']%>";
          minute[minute.length] = "m<%=combo['id']%>";
          second[second.length] = "s<%=combo['id']%>";
        </script>
        <% else %>
        <span class="pull-left countdown">
          长期有效
        </span>
        <% end %>
        <span class="pull-right">
          <a class="btn btn-danger btn-small add_loading" href="javascript:void(0);" value="<%= ims_orders_new_path(:combo_id => combo['id'])%>">点击购买</a>
        </span>
      </p>
    </div>

  </div>
</div>
<% end %>

<% end %>
<div class="intime-btm intime-btm-index">
  <%= image_tag "ims/intime-btm.png" %>
</div>

app/views/ims/combos/_list.html.erb
<% if nil %>

<% @combos.each do |combo| %>
<div class="module module-ele paginate-content">
  <div class="module-content module-content-img">
    <div class="suit-box clearfix">
      <div class="row-fluid">
        <div class="span12">
          <div class="suit-left">
            <a class="img-box img-posi" href="<%= ims_combo_path(id: combo["id"], t: Time.now.to_i) %>">
              <%= image_tag Combo.img_url(combo) %>
            </a>

            <p class="combo_text combo_two_line_text">
              <a href="<%= ims_combo_path(id: combo["id"], t: Time.now.to_i) %>"><%= sanitize format_text(combo["desc"]) %></a>
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="clearfix countdown-browser combo_text">
      <p class="pull-left price-box">
        <span class="txt3 price price-span">
          品牌：<em><%= combo["brands"].collect{|brand| brand["name"]}.uniq.join(", ") %></em>
        </span>
      </p>
      <p class="pull-left price-box">
        <span class="txt3 price price-span">
          打包价：<em>¥<%= combo["isInPromotion"] ? (BigDecimal(combo["price"].to_s) - BigDecimal(combo["discountAmount"].to_s)) : combo["price"] %></em>
        </span>

      </p>
      <p class="pull-left price-box">
        <% expired_in = (combo["expireDate"].to_time - 8.hour).to_i - Time.now.to_i
        expired_in = expired_in > 0 ? expired_in : nil %>
        <% if expired_in.present? %>
        <span class="pull-left countdown">
          <em id="d<%=combo['id']%>">0</em><span>天</span><em id="h<%=combo['id']%>">00</em>:<em id="m<%=combo['id']%>">00</em>:<em id="s<%=combo['id']%>">00</em><span>后下架</span>
        </span>
        <script type="text/javascript">
          tms[tms.length] = "<%=expired_in %>";
          day[day.length] = "d<%=combo['id']%>";
          hour[hour.length] = "h<%=combo['id']%>";
          minute[minute.length] = "m<%=combo['id']%>";
          second[second.length] = "s<%=combo['id']%>";
        </script>
        <% else %>
        <span class="pull-left countdown">
          长期有效
        </span>
        <% end %>
        <span class="pull-right">
          <a class="btn btn-danger btn-small" href="<%= ims_orders_new_path(:combo_id => combo['id'])%>">点击购买</a>
        </span>
      </p>
    </div>

  </div>
</div>
<% end %>

<% end %>


<% @combos.each do |combo| %>
  <span class="combo_wrapper paginate-content">
    <span class="thumbnail">
    <a class="img-box img-posi" href="<%= ims_combo_path(id: combo["id"], t: Time.now.to_i) %>">
      <%= image_tag Combo.img_url(combo) %>
    </a>

    <div class="clearfix countdown-browser combo_text">

      <p class="pull-left price-box combo_two_line_text">
        <a href="<%= ims_combo_path(id: combo["id"], t: Time.now.to_i) %>"><%= sanitize format_text(combo["desc"]) %></a>
      </p>

      <p class="pull-left price-box">
        <span class="price price-span">
          打包价：
          <em>¥<%= combo["isInPromotion"] ? (BigDecimal(combo["price"].to_s) - BigDecimal(combo["discountAmount"].to_s)) : combo["price"] %></em>
        </span>
        <% if (origin_price = combo["originPrice"]).present? %>
        <span class="price-span-orignal">￥<%= origin_price %></span>
        <% end %>
      </p>

      <p class="pull-left price-box">
        <% expired_in = (combo["expireDate"].to_time - 8.hour).to_i - Time.now.to_i
        expired_in = expired_in > 0 ? expired_in : nil %>
        <% if expired_in.present? %>
          <span class="pull-left countdown">
            <em id="d<%=combo['id']%>">0</em><span>天</span><em id="h<%=combo['id']%>">00</em>:<em id="m<%=combo['id']%>">00</em>:<em id="s<%=combo['id']%>">00</em><span>后下架</span>
          </span>
          <script type="text/javascript">
            tms[tms.length] = "<%=expired_in %>";
            day[day.length] = "d<%=combo['id']%>";
            hour[hour.length] = "h<%=combo['id']%>";
            minute[minute.length] = "m<%=combo['id']%>";
            second[second.length] = "s<%=combo['id']%>";
          </script>
        <% else %>
          <span class="pull-left countdown">
            长期有效
          </span>
        <% end %>
      </p>

    </div>
    </span>
  </span>
<% end %>

app/views/ims/combos/_product.html.erb
<div class="span4">
  <div class="combos-product">
  <!--  搭配详情api接口，如果商品类型为系统商品（1），那么images的最后一个为主图  -->
    <% img_url =  product[:images].present? ? (product['product_type'] == 1 ? product[:images].last['url'] : product[:images].first['url']) : Settings.default_image_url.product.small %>
    <% if @remote_combo[:data][:is_online] && product[:is_online] %>
    <span class="img-spa" data="<%=product[:id]%>">
      <%= image_tag img_url %>
    </span>
    <% else %>
    <span class="img-spa" data="<%=product[:id]%>">
      <%= image_tag img_url %>
    </span>
    <% end %>
    <p>
      <span class="price">￥<%= product[:price] %></span>
      <% if (unitprice = product[:unitprice]).present? %>
        <span class="origin_price">￥<%= unitprice %></span>
      <% end %>
    </p>
    <% if @remote_combo[:data][:is_online] && product[:is_online] %>
    <%= link_to "点击购买", 'javascript:void(0);', class: "btn btn-danger btn-mini btn-block payment_product", value: ims_orders_new_path(:product_id => product[:id], :store_id => @store_id, :combo_id => @remote_combo[:data][:id]) %>
    <% else %>
    <a href="javascript:void(0);" class="btn btn-grey btn-mini btn-block">已售罄</a>
    <% end %>
  </div>
</div>

app/views/ims/combos/ajax.js.erb
<% if @product.present? %>
$("#p_modal_content").html("<%=j render 'ajax'%>");
$("#p_pop").modal();
<% else %>
 error_modal("暂无产品信息");
<%end %>

app/views/ims/combos/list.json.erb
{"status": true, "page": <%= @search[:page] %>, "per_page": <%= @search[:per_page] %>, "count": <%= @search[:count] %>, "group_id": "<%= @search[:group_id] %>", "html": <%=raw render("list.html.erb").to_json %> }