config/routes.rb
class VersionConstraint
  def initialize(*version)
    @version = version[0].to_i unless version.nil?
    @version = 2*100+1*10+1 if @version.nil? || @version ==0
  end

  def matches?(request)
    current_ver = request.query_parameters[:client_version]
    return false if current_ver.nil?
    current_ver_value = 0
    current_ver.split('.'). each_with_index do |v,i|
      break if i > 2
      current_ver_value += v.to_i*(10 ** (2-i))
    end
    return @version <= current_ver_value
  end
end

IntimeService::Application.routes.draw do

  get "comment/get_list"

  match "wxmsg/update"=>"wxReply#update"

  match "version/latest"=>"version#latest"
  match "version/insert"=>"version#insert"

  match "storecoupon/consume"=>"storeCoupon#consume"
  match "storecoupon/logs"=>"storeCoupon#logs"
  match "storecoupon/void"=>"storeCoupon#void"

  scope :module => "v22" do
    constraints VersionConstraint.new do
     match "promotion/list" =>"promotion#list"
     match "storepromotion/list"=>"storePromotion#list"
     match "storepromotion/detail"=>"storePromotion#detail"
     match "specialtopic/list"=>"specialTopic#list"
     match "banner/list"=>"banner#list"
    end
  end
  scope :module=>'front' do
    get '/auth/:provider/callback', to: 'sessions#create'
    delete '/logout', to: 'sessions#destory'
    get '/login', to: 'sessions#login'
  end

  match "hotword/list"=>"hotword#list"
  match "banner/list"=>"banner#list"

  match "store/list"=>"store#list"
  match "store/all"=>"store#list"
  match "store/detail"=>"store#detail"
  match "store/:id"=>"store#index"

  match "brand/list"=>"brand#list"
  match "brand/all"=>"brand#list"
  match "brand/groupall"=>"brand#list_by_group"

  match "tag/list"=>"tag#list"
  match "tag/all"=>"tag#list"

  match "specialtopic/list" => "specialTopic#list"

  match "product/search" => "product#search"
  match "product/list" => "product#list"

  match "promotion/list" => "promotion#list"

  match "wx_object/search" => "wxobject#validate", :via=>:get, :defaults=>{:format=>'html'}
  match "wx_object/search" => "wxobject#search", :via=>:post, :defaults=>{:format=>'xml'}

  match "card/find"=>"card#find"

  resources :special_topic, only: [:index] do
    collection do
      get :get_list
    end
  end

  resources :promotion, only: [] do
    collection do
      get :get_list
    end
  end

  scope module: :front do
    resources :promotions, only: [:index, :show] do
      collection do
        get :get_list
      end
    end

    resources :products, only: [:index, :show]
  end

  resources :special_topic, only: [:index] do
    collection do
      get :get_list
    end
  end

  resources :promotion, only: [] do
    collection do
      get :get_list
    end
  end

  scope module: :front do
    resources :promotions, only: [:index, :show] do
      collection do
        get :get_list
      end
    end

    resources :products, only: [:index, :show]
  end

  match "product/:id" => "product#show"
  match "promotion/:id" => "promotion#show"

  namespace :front do
       resources :exorders do
         collection do
           get 'show'
         end
       end

    get '/hotwords',                to: 'common#hotwords'
    get '/tags',                    to: 'common#tags'
    get '/brands',                  to: 'common#brands'
    get '/stores',                  to: 'common#stores'

    get '/my_favorite',             to: 'users_center#my_favorite'
    get '/my_share',                to: 'users_center#my_share'
    get '/my_promotion',            to: 'users_center#my_promotion'
    get '/follows',                 to: 'users_center#follows'
    get '/fans',                    to: 'users_center#fans'
    get '/my_profile',              to: 'users_center#profile'
    get '/his_favorite/:userid',    to: 'users_center#his_favorite',  as: :his_favorite
    get '/his_promotion/:userid',   to: 'users_center#his_promotion', as: :his_promotion
    get '/his_share/:userid',       to: 'users_center#his_share',     as: :his_share
    get '/his_info/:userid',        to: 'users_center#his_info',      as: :his_info
    get '/his_profile/:userid',     to: 'users_center#his_profile',   as: :his_profile
    post '/follow/:id',             to: 'users_center#follow',        as: :follow
    post '/unfollow/:id',           to: 'users_center#unfollow',      as: :unfollow
    get  '/about',                  to: 'about#index',                as: :about
    get  '/feedback',               to: 'about#feedback',             as: :feedback
    post '/feedback',               to: 'about#create_feedback',      as: :create_feedback

    get '/order/create' ,            to: 'orders#create'
    get 'address/create',           to: 'addresses#create'
    get 'address/update',           to: 'addresses#update'

    get  '/my_comments',            to: 'comments#my_comments',       as: :my_comments

    resources :products, :only=>[:index, :show] do
      collection do
        get :his_favorite_api, :path => :his_favorite_api
        get :my_favorite_api
        get :my_share_list_api
        get :sort_list
        get :list_api
        get :list
        get :search_api
      end

      member do
        post :favor
        post :unfavor
        post :download_coupon
        post :comment
      end
    end
    resources :promotions, :only=>[:index, :show] do
      collection do
        get :get_list
      end

      member do
        post :favor
        post :unfavor
        post :download_coupon
        post :comment
      end
    end

    resources :stores, only: [:show] do
      member do
        get :promotions
      end
    end

    resources :specials, :only => [:index] do
      collection do
        get :get_list
      end
    end

    resources :comments  do
      collection do
        get  :get_list
      end
    end

    resources :orders, except: [:edit, :update] do
      collection do
        post :computeamount
        post :confirm
      end

      member do
        get :pay
      end
    end
    resources :addresses, only: [:index, :create, :update, :destroy]
    resources :rmas do
      collection do
        get :order_index
      end
    end

    resources :coupons, only: [:index]

    resources :vouchers, only: [:index, :show] do
      collection do
        get  :exchange_info
        get  :binding_card

        post :bindcard
      end

      member do
        post :void
      end
    end

    resources :storepromotions, only: [:index, :show] do
      member do
        post :exchange
        post :amount
      end
    end
    get '/profile', to: 'profile#index'
    get '/profile/return_policy', to: 'profile#return_policy'
    get '/profile/edit', to: 'profile#edit'
    put '/profile/update', to: 'profile#update'

    get '/supportshipments', to: 'environment#supportshipments'

  end

  namespace :ims do

    resources :payments,only: [] do
      collection do
        get "go"
        get "alipay_success"
      end
    end

    resources :weixins, only: [] do
      collection do
        get "auth"
        get "login"
        get "login_success"
        get "get_access_token"
        get "qrcode"
      end
    end
    resources :sms_codes, only: :create
    resources :addresses do
      collection do
        get "list"
      end
    end

    resource :auth do
      get 'forward'
      get 'get_user_token'
    end
    resources :stores, only: [:show]
    resources :combos, only: [:show, :destroy, :index] do
      collection do
        post 'upload'
        get 'ajax'
      end
    end
    resources :accounts, only: [:new, :create] do
      collection do
        get   :mine
        get   :barcode
        get   :phone_page
        get   :verify_identify_phone
        get   :verify_identify_sms_code
        get   :verify_phone
        get   :verify_sms_code
        post  :resend_sms
        get   :set_identity_no_page
        get   :set_identity_no
        get   :before_reset_password_page
        get   :reset_password_page
        get   :reset_password
        get   :change_password_page
        get   :change_password
        get   :set_id_page
        post  :set_id
      end
    end
    resources :cards, only: [:index] do
      collection do
        get     :recharge
        get     :resend_gift
        get     :give_page
        get     :accept
        get     :accepted_page
        get     :give
        get     :refuse
        get     :agreement
      end
    end
    get 'cards/gift_page/:charge_no', to: 'cards#gift_page'
    resources :card_orders, only: [:new, :create, :show] do
      collection do
        get :list
        get :my_list
        get :received_list
        get :check_status
      end
    end
    match "card_orders_pay" => "card_orders#new"
    match "orders_new" => "orders#new"
    match "orders_show" => "orders#show"
    resources :favorites, only: [] do
      collection do
        get  :stores_list
        get  :combos_list
        get  :list
        post :favor
        post :unfavor
      end
    end
    resources :recharge_histroy, only: [:index]
    resources :orders, only: [:index, :new, :create, :show] do
      member do
        put :change_state
        post :payments
        get :notice_success
        put :update_promotion
      end

      collection do
        get :totalamount
      end
      resources :returns_reasons, only: [:new, :create] do
        member do
          put :cancel
        end
        collection do
          get "result"
        end
      end
    end

    

    namespace :store do
      root :to => "home#index"
      post "login" => "home#login"
      get 'check_code' => 'home#check_code'
      resources :invitation_codes, only: [:new, :create, :update] do
        collection do
          get :upgrade
        end
      end
      resources :sales_codes, only: :create
      resources :sells, only: :index do
        member do
          put :update_is_online
        end
      end
      resources :suggesstions, only: [:new, :create]
      resources :products do
        member do

app/models/api/order.rb
# encoding: utf-8
module API
  class Order < API::Base

    STATUSES = {
      unpaid:     0,    # 创建未支付
      paid:       1,    # 已支付
      approval:   2,    # 订单审核通过
      unshipped:  14,   # 订单准备发货
      shipped:    15,   # 订单已发货
      received:   16,   # 用户已签收
      rejected:   10    # 用户拒收
    }

    TYPES = {
      unpaid:     0,    # 待支付
      unreceived: 1,    # 待收货
      completed:  2,    # 已完成
      cancelled:  3     # 已取消
    }

    class << self
      def index(req, params = {})
        post(req, params.merge(path: 'order/my'))
      end

      def create(req, params = {})
        post(req, params.merge(path: 'product/order'))
      end

      def show(req, params = {})
        post(req, params.merge(path: 'order/detail'))
      end

      def destroy(req, params = {})
        post(req, params.merge(path: 'order/void'))
      end

      def new(req, params = {})
        post(req, params.merge(path: 'product/detail4p'))
      end

      # 计算 运费 总积分 总金额 商品价格
      def computeamount(req, params = {})
        post(req, params.merge(path: 'product/computeamount'))
      end

      # 订单能否取消
      def can_cancel?(statust)
        STATUSES.values_at(:unpaid, :paid, :approval).map(&:to_s).include?(statust.to_s)
      end

      # 能否支付
      def can_payment?(statust)
        STATUSES[:unpaid].to_s == statust.to_s
      end

      # retrieve wx pay redirect url
      def wxpay_url(req, params ={})
        post(req,params.merge(path:'order/wxhtmlpay'))
      end
    end
  end
end

app/models/ims/assistant.rb
# encoding: utf-8
class Ims::Assistant < Ims::Base

  def self.update_is_online(req, params = {})
    post(req, params.merge(path: 'assistant/combo_status_update'))
  end

  def self.brands(req, params={})
    post(req, params.merge(path: 'assistant/brands'))
  end

end

app/models/ims/base.rb
# encoding: utf-8
class Ims::Base
  extend Ims::Restful

end

app/models/ims/combo.rb
# encoding: utf-8
class Ims::Combo < Ims::Base

  class << self
    def list(req, params={})
      post(req, params.merge(path: 'assistant/combos'))
    end

    def create(req, params={})
      post(req, params.merge(path: 'combo/create', content_type: :json))
    end

    def show(req, params = {})
      post(req, params.merge(path: 'combo/detail'))
    end

    def update(req, params = {})
      post(req, params.merge(path: 'combo/update', content_type: :json))
    end

    def upload_img(req, params ={})
      post(req, params.merge(path: 'resource/upload'))
    end

    def online_num(req, params = {})
      post(req, params.merge(path: 'assistant/combos_online_count'))
    end

    def delete(req, params = {})
      post(req, params.merge(path: 'combo/delete'))
    end

  end

end

app/models/ims/des.rb
# encoding: utf-8
class Ims::Des
  require 'openssl'  
  require 'base64'  
  ALG = 'DES-ECB'  
  KEY = "intimeit"     #你的密钥
  DES_KEY = "intimeit"          #任意固定的值
  
  #加密  
  def encode(str)  
    des = OpenSSL::Cipher::Cipher.new(ALG)  
    des.encrypt
    des.key=KEY
    cipher = des.update(str)  
    cipher << des.final  
    return Base64.encode64(cipher) #Base64编码，才能保存到数据库
  end  
  
  #解密    
  def decode(str)  
    str = Base64.decode64(str)  
    des = OpenSSL::Cipher::Cipher.new(ALG)  
    des.pkcs5_keyivgen(KEY, DES_KEY)  
    des.decrypt  
    des.update(str) + des.final  
  end  
end

app/models/ims/giftcard.rb
# encoding: utf-8
class Ims::Giftcard < Ims::Base

  # 默认礼品卡Id
  DEFAULT_ID = '1'

  # 导购获取可选择礼品卡列表
  def self.all(req, params = {})
    post(req, params.merge(path: "assistant/gift_cards"))
  end

  # 普通用户-已绑定卡的礼品卡概述（在API部门是否绑定）
  def self.my(req, params = {})
    post(req, params.merge(path: 'giftcard/my'))
  end

  # 普通用户通过手机号得到卡信息，同时进行绑定
  def self.bind(req, params = {})
    post(req, params.merge(path: 'giftcard/bind'))
  end

  # 判断手机号是否已经绑定（在集团信息部是否绑定）
  def self.isbind(req, params = {})
    post(req, params.merge(path: 'giftcard/isbind'))
  end

  def self.create(req, params = {})
    post(req, params.merge(path: 'giftcard/create'))
  end

  # 普通用户购买充值卡，列表
  def self.items(req, params = {})
    post(req, params.merge(path: 'giftcard/items'))
  end

  # 普通用户购买充值卡
  def self.transfer_detail(req, params = {})
    post(req, params.merge(path: 'giftcard/transfer_detail'))
  end

  # 获取礼品卡赠送信息 通过赠送记录 id
  def self.trans_detail2(req, params = {})
    post(req, params.merge(path: 'giftcard/trans_detail2'))
  end

  def self.detail(req, params = {})
    post(req, params.merge(path: 'giftcard/detail'))
  end

  def self.trans_detail(req, params = {})
    post(req, params.merge(path: 'giftcard/trans_detail'))
  end

  def self.receive(req, params = {})
    post(req, params.merge(path: 'giftcard/receive'))
  end

  def self.recharge(req, params = {})
    post(req, params.merge(path: 'giftcard/recharge'))
  end

  def self.send(req, params = {})
    post(req, params.merge(path: 'giftcard/send'))
  end

  def self.sendex(req, params = {})
    post(req, params.merge(path: 'giftcard/sendex'))
  end

  def self.changepwd(req, params = {})
    post(req, params.merge(path: 'giftcard/change_pwd'))
  end

  def self.resetpwd(req, params = {})
    post(req, params.merge(path: 'giftcard/reset_pwd'))
  end

  def self.refuse(req, params = {})
    post(req, params.merge(path: 'giftcard/refuse'))
  end

  def self.refusebytransid(req, params = {})
    post(req, params.merge(path: 'giftcard/refusebytransid'))
  end

  def self.list(req, params = {})
    post(req, params.merge(path: 'giftcard/list'))
  end

end

app/models/ims/income.rb
# encoding: utf-8

class Ims::Income < Ims::Base

  class << self

    def index(req, params={})
      post(req, params.merge(path: 'assistant/income_history'))
    end

    def list(req, params={})
      post(req, params.merge(path: 'assistant/income_received'))
    end

    def frozen(req, params={})
      post(req, params.merge(path: 'assistant/income_frozen'))
    end

    def my(req, params={})
   	  post(req, params.merge(path: 'assistant/income'))
    end

    def banks(req, params = {})
      post(req, params.merge(path: 'assistant/avail_banks'))
    end

    def apply(req, params = {})
      post(req, params.merge(path: 'assistant/income_request'))
    end

    def pending(req, params = {})
      post(req, params.merge(path: 'assistant/income_requesting'))
    end

    def latest_bank(req, params = {})
      post(req, params.merge(path: 'assistant/latest_bankinfo'))
    end
  end

end

app/models/ims/order.rb
# encoding: utf-8
class Ims::Order < Ims::Base

  class << self

    def new(req, params = {})
      post(req, params.merge(path: 'combo/detail4p'))
    end

    def my(req, params = {})
      post(req, params.merge(path: 'order/my'))
    end

    def detail(req, params = {})
      post(req, params.merge(path: 'order/detail', api_path: true))
    end

    # 计算 运费 总积分 总金额 商品价格
    def computeamount(req, params = {})
      post(req, params.merge(path: 'combo/computeamount'))
    end

    def update_promotion(req, params = {})
      post(req, params.merge(path: 'order/fill_pro', content_type: :json))
    end

  end

end

app/models/ims/product_brand.rb
# encoding: utf-8
class Ims::ProductBrand < Ims::Base

 class << self
   # def list(req, params={})
   #   post(req, params.merge(path: 'ims/assistant/brands'))
   # end
 end

end

app/models/ims/product_category.rb
# encoding: utf-8
class Ims::ProductCategory < Ims::Base

  class << self
    def list(req, params={})
      post(req, params.merge(path: 'assistant/category_sizes'))
    end
  end

end

app/models/ims/product_coding.rb
# encoding: utf-8
class Ims::ProductCoding < Ims::Base

  class << self
    def list(req, params={})
      post(req, params.merge(path: 'assistant/salescodes'))
    end

    def create(req, params={})
      post(req, params.merge(path: 'assistant/salescode_add'))
    end
  end

end

app/models/ims/unauthorized.rb
# encoding: utf-8
class Ims::Unauthorized < StandardError
end

app/views/ims/orders/_list.html.erb
  <% @orders.each do |order| %>
  <div class="module common-white paginate-content" id="order_<%= order["order_no"] %>">
    <div class="module-state">
      <div class="row-fluid">
        <div class="span6"><span class="txt3">订单状态：<em class="status"><%= order["status"] %></em></span></div>
        <div class="span6 text-right"><span class="txt3">订单金额：<em>￥<%= order['amount'] %></em></span></div>
      </div>
    </div>

    <% order["products"].each do |product| %>
      <div class="indent-head">
        <div class="row-fluid">
           <div class="span3">
               <div class="detail-imgbox">
                <img src="<%=product["image"] %>">
               </div>
           </div>
           <div class="span9">
               <div class="price-detail">
                   <h3 class="one-line"><%= product["name"] %></h3>
                   <p class="txt4 clearfix">
                     <span class="pull-left">微信价：<em>￥<%= product["price"] %></em></span>
                   </p>
                   <p class="txt4 clearfix">
                     <span class="pull-left"><%= product["productdesc"] %></span>
                   </p>
               </div>
           </div>
        </div>
      </div>

    <% end %>

    <div class="row-fluid">
      <div class="span12">
        <div class="detail-block detail-contact-bd">
        <%= link_to "javascript:void(0);", class: "order_show", value: ims_orders_show_path(id: order["order_no"]) do %>
        <div class="txt-block">
          <p class="txt4 clearfix">
            <span class="pull-left">
              <b>订单号：<%= order['order_no'] %></b>
            </span>
          </p>
          <p class="txt4 clearfix"><span><b>收货人：<%= order['shipping_name'] %></b></span></p>
          <p class="txt4 clearfix"><span><b>下单时间：<%= l order['create_date'].to_time %></b></span></p>
        </div>
        <% end %>

        <% if order["status_i"] == 0 %>
          <p class="immediate-payment">
            <a class="btn btn-danger btn-small payment" href="javascript:void(0);" orderno="<%= order['order_no'] %>" amount="<%= order["amount"] %>">立即支付</a>
          </p>
        <% end %>
        </div>
      </div>
    </div>
  </div>
  <% end %>

<script>
  $(function(){
    $(".detail-imgbox").each(function(){
      $(this).css("height", $(this).width())
      $(this).css("line-height", $(this).height()+"px")
    });
  })
</script>

app/views/ims/orders/index.html.erb
<div class="wrap-content">

  <% if @orders.present? %>
    <%= render "list", orders: @orders %>
  <% else %>
    <%= render 'ims/shared/empty' %>
  <% end %>
</div>

<%= hidden_field_tag "count", @search[:data][:totalcount] %>
<%= hidden_field_tag "page", @search[:data][:pageindex] %>
<%= hidden_field_tag "per_page", @search[:data][:pagesize] %>

<% content_for :javascripts do %>
  <script>
    $(function(){

      var inLoading = false

      $(document).on("click", ".order_show", function(){
        url = $(this).attr("value")
        $("#loading-box").modal()
        setTimeout(function(){
          window.location.href = url
        }, 1)
      })

      $(document).on("click", ".payment", function(){
        $("#loading-box").modal()
        orderno = $(this).attr("orderno")
        totalamount = $(this).attr("amount")
        $.post("/ims/orders/"+orderno+"/payments", {money: totalamount, from_page: "orders_list"}, function(data){}, "script")
      })

      $(window).scroll(function(){
        var htmlHeight=document.body.scrollHeight
        var clientHeight=document.body.clientHeight
        var scrollTop=document.body.scrollTop
        var count = parseInt($("#count").attr("value"))
        var page = parseInt($("#page").attr("value"))
        var per_page = parseInt($("#per_page").attr("value"))

        if(scrollTop+clientHeight == htmlHeight && !inLoading){
          if(page * per_page < count && !inLoading){
            inLoading = true
            $("#bottom-loading-box").modal();
            $.get("/ims/orders", {page: page + 1, per_page: per_page}, function(data){
              if(data["status"] == true){
                $(".paginate-content:last").after(data["html"])
                $("#count").attr("value", data["count"])
                $("#page").attr("value", data["page"])
                $("#per_page").attr("value", data["per_page"])
              }
              $("#bottom-loading-box").modal('hide');
              inLoading = false
            }, "json")
          }
        }

      })
    })
  </script>
<% end %>

app/views/ims/orders/list.json.erb
{"status": true, "page": <%= @search["data"]["pageindex"] %>, "per_page": <%= @search["data"]["pagesize"] %>, "count": <%= @search["data"]["totalcount"] %>, "html": <%=raw render("list.html.erb", orders: @orders).to_json %> }

app/views/ims/orders/notice_success.html.erb
  <div class="module module-white module-user-card">
    <h1>恭喜您，商品购买成功！</h1>
    <div class="module-table-box">
      <table class="table table-bordered">
        <tbody>
          <tr>
            <td>订单金额</td>
            <td>￥<%= @order[:totalamount] %></td>
          </tr>
          <tr>
            <td>订单编号</td>
            <td><%= @order[:orderno] %></td>
          </tr>
        </tbody>
      </table>
    </div>


    <div class="module-btn text-center">
      <button class="btn btn-large btn-danger btn-block" id="show_button" value="<%= ims_order_path(@order[:orderno]) %>">查看订单详情</button>
    </div>
    <br/>

    <% if @order[:can_like_miniyin] %>
    <div class="module module-notice">
      <p style="color: red">如果您还未关注迷你银公众号，后期将无法查看您的订单等信息，请务必点击以下链接关注我们：</p>
      <a href="http://mp.weixin.qq.com/s?__biz=MzA3NTQyMzcyNw==&mid=200211171&idx=1&sn=212ce2198c574df483359d817ec7a4a4&scene=1&from=singlemessage&isappinstalled=0&key=bdc0fc08be7dd6d4253502098c36d92c47b6b8d0de93638f587afcd53b17d39290dc3b1a9225eff6857d3e7a6d801fdd&ascene=0&uin=Mjk5NzcyNjE1" style="color: black;"><div class="well" style="padding: 4px"><%= image_tag "ims/logo_intime_s.jpg", width: 40, height: 40 %> 关注迷你银<i class="fa fa-chevron-right" style="font-size: 25px; float: right; margin-right: 10px; margin-top: 8px; color: #505050"></i></div></a>
    </div>
    <% end %>

  </div>



  <% content_for :javascripts do %>
    <script>
      $(function(){

        $(document).on("click", "#follow_button, #show_button", function(){
          url = $(this).attr("value")
          $("#loading-box").modal()
          setTimeout(function(){
            window.location.href = url
          }, 1)
        })
      })
    </script>
  <% end %>

app/views/ims/orders/payments.js.erb
$("#loading-box").modal("hide")

<% if @order[:paymentcode] == "270" %>

WeixinJSBridge.invoke('getBrandWCPayRequest', {
"appId" : "<%= @weixin_key[:app_id] %>", //公众号名称，由商户传入
"timeStamp" : "<%= @time_val.to_i %>", //时间戳
"nonceStr" : "<%= raw @noncestr_val %>", //随机串
"package" : "<%= raw @package_val %>",//扩展字段，由商户传入
"signType" : "SHA1", //微信签名方式:sha1
"paySign" : "<%= @paySign_val %>" //微信签名
},function(res){
  orderno = "<%= @orderno %>"
  from_page = "<%= @from_page %>"
  if(res.err_msg == "get_brand_wcpay_request:ok"){
      // get_brand_wcpay_request:ok 发送成功
    if(from_page == "orders_new"){
      window.location.href = "/ims/orders/"+orderno+"/notice_success"
    }else if(from_page == "orders_show" || from_page == "orders_list"){
      $.get("/ims/orders/"+orderno, {}, function(data){
        status = data["status"]
        statust = data["statust"]
        canvoid = data["canvoid"]
        canrma = data["canrma"]
        if(from_page == "orders_show"){
          if(statust == 0){
            $("#order-notice").show()
            $("#payment").parent().show()
          }else if(statust == 1){
            $("#order-notice").hide()
            $("#payment").parent().hide()
          }
          if(canvoid){
            $("#cancel_order").parent().show()
          }else{
            $("#cancel_order").parent().hide()
          }
          if(canrma){
            $("#rmas").parent().show()
          }else{
            $("#rmas").parent().hide()
          }
          $("#order_status").text(status)
        }else if(from_page == "orders_list"){

          order_doc = $("#order_"+orderno)
          order_doc.find(".status").text(status)

          if(statust == 0){
            order_doc.find(".payment").show()
          }else if(statust == 1){
            order_doc.find(".payment").hide()
          }
        }

      }, "json")
    }


  }else if(res.err_msg == "get_brand_wcpay_request:cancel"){
    if(from_page == "orders_new"){
      $("#orderno").attr("value", orderno)
      $("#loading-box").modal()
      setTimeout(function(){
        window.location.href = "/ims/orders_show?id="+orderno
      }, 1)
    }
     // get_brand_wcpay_request:cancel 用户取消

  }else if(res.err_msg == "get_brand_wcpay_request:fail"){
  }else{
    error_modal(res.err_msg)
  }

// WeixinJSBridge.log(res.err_msg);
// alert(res.err_code+res.err_desc);
});


<% else %>

window.location.href = "/ims/payments/go?orderno=<%=@orderno%>&order_price=<%=@order_price%>&url=<%=u @url %>";

<% end %>